extends:
  - eslint:recommended
parser: babel-eslint
parserOptions:
  sourceType: module
  ecmaFeatures:
    jsx: true
    es6: true
    classes: true
    modules: true
env:
  node: true
  mocha: true
  es6: true
plugins:
  - prettier
rules:
  prettier/prettier: 2
  complexity: [0, 4]
  eqeqeq: 2
  quotes: [2, double]
  no-console: 1
  no-dupe-keys: 2
  no-else-return: 2
  no-empty: 2
  no-eq-null: 0
  no-extra-boolean-cast: 2
  no-extra-semi: 2
  no-mixed-spaces-and-tabs: 2
  no-param-reassign: 1
  no-redeclare: 2
  no-underscore-dangle: 2
  no-unreachable: 2
  no-unused-vars: 2
  no-use-before-define: 2
  no-useless-constructor: 2
  no-useless-escape: 2
  object-curly-spacing: [2, always]
  object-shorthand:
    - 2
    - methods
    - ignoreConstructors: true
      avoidExplicitReturnArrows: true
  use-isnan: 2